export const transferProvidersSeed = [
  {
    id: "taptap-send",
    name: "Taptap Send",
    logo_url: "/logos/taptapsend.png",
    tagline: "Best overall when you need strong XOF payout with minimal friction.",
    best_for: "Fast mobile wallet delivery to West Africa",
    availability_summary: "Strong for card-funded diaspora transfers with consistent wallet speed.",
    corridor_focus: "US, UK, and Europe to Francophone West Africa",
    payout_networks: ["Mobile wallet", "Bank deposit"],
    strengths: ["Strong exchange quality", "Fast wallet settlement", "Low fee positioning"],
    exchange_rate_score: 9.1,
    exchange_rate: 1386.2,
    fee_score: 8.9,
    speed_score: 9.2,
    ease_score: 8.8,
    efficiency_score: 8.9,
    mobile_wallet_speed: 9.4,
    bank_deposit_speed: 8.6,
    referral_link: "https://www.taptapsend.com",
    sort_order: 10,
    active: true
  },
  {
    id: "lemfi",
    name: "Lemfi",
    logo_url: "/logos/lemfi.png",
    tagline: "Balanced payout quality with strong bank deposit execution.",
    best_for: "Bank deposits and frequent repeat senders",
    availability_summary: "Well-suited for senders comparing payout quality and account-based delivery.",
    corridor_focus: "North America and Europe into major African banking corridors",
    payout_networks: ["Bank deposit", "Wallet in selected corridors"],
    strengths: ["Strong bank payout speed", "Good fee consistency", "Clean app experience"],
    exchange_rate_score: 8.8,
    exchange_rate: 1384.75,
    fee_score: 8.7,
    speed_score: 8.9,
    ease_score: 8.6,
    efficiency_score: 8.7,
    mobile_wallet_speed: 8.8,
    bank_deposit_speed: 9.1,
    referral_link: "https://www.lemfi.com",
    sort_order: 20,
    active: true
  },
  {
    id: "nala",
    name: "NALA",
    logo_url: "/logos/nala.png",
    tagline: "Consumer-friendly UX with reliable everyday diaspora sending flows.",
    best_for: "Simple repeat transfers from mobile-first users",
    availability_summary: "Good for straightforward recurring transfers where ease matters as much as rate.",
    corridor_focus: "US, UK, and EU diaspora corridors into Africa",
    payout_networks: ["Bank deposit", "Mobile wallet"],
    strengths: ["High ease-of-use", "Solid wallet support", "Strong recurring-send fit"],
    exchange_rate_score: 8.7,
    exchange_rate: 1382.53,
    fee_score: 8.5,
    speed_score: 8.8,
    ease_score: 8.9,
    efficiency_score: 8.5,
    mobile_wallet_speed: 8.7,
    bank_deposit_speed: 8.4,
    referral_link: "https://www.nala.com",
    sort_order: 30,
    active: true
  },
  {
    id: "send-app",
    name: "Send App",
    logo_url: "/logos/sendapp.png",
    tagline: "Useful when Flutterwave-linked rails give a smoother payout path.",
    best_for: "Flutterwave-connected payout routes",
    availability_summary: "A pragmatic option when payout rail availability matters more than absolute rate leadership.",
    corridor_focus: "Diaspora corridors supported through Flutterwave-linked infrastructure",
    payout_networks: ["Bank deposit", "Wallet in supported markets"],
    strengths: ["Reasonable pricing", "Practical payout coverage", "Simple checkout flow"],
    exchange_rate_score: 8.4,
    exchange_rate: 1379.4,
    fee_score: 8.6,
    speed_score: 8.3,
    ease_score: 8.7,
    efficiency_score: 8.4,
    mobile_wallet_speed: 8.5,
    bank_deposit_speed: 8.2,
    referral_link: "https://send.flutterwave.com",
    sort_order: 40,
    active: true
  },
  {
    id: "remitly",
    name: "Remitly",
    logo_url: "/logos/remitly.png",
    tagline: "Broad brand familiarity and dependable delivery for mainstream senders.",
    best_for: "Brand-trust oriented customers",
    availability_summary: "Often chosen when familiarity and predictable experience outweigh pure payout optimization.",
    corridor_focus: "Large global diaspora corridors across bank and cash-out routes",
    payout_networks: ["Bank deposit", "Cash pickup", "Mobile wallet"],
    strengths: ["Strong consumer trust", "Wide corridor coverage", "Reliable delivery"],
    exchange_rate_score: 8.1,
    exchange_rate: 1375.15,
    fee_score: 8,
    speed_score: 8.2,
    ease_score: 8.6,
    efficiency_score: 8,
    mobile_wallet_speed: 8,
    bank_deposit_speed: 8.5,
    referral_link: "https://www.remitly.com",
    sort_order: 50,
    active: true
  }
] as const

export type SeededTransferProvider = (typeof transferProvidersSeed)[number]