create extension if not exists pgcrypto;

create table if not exists public.jit_orders (
  id text primary key,
  trace_id text not null,
  product_id text not null,
  product_type text not null,
  customer_reference text not null,
  recipient_label text not null,
  amount numeric not null,
  currency text not null default 'XOF',
  status text not null default 'received',
  quoted_price numeric,
  provider_cost numeric,
  margin numeric,
  pricing_input_amount numeric,
  pricing_provider_cost numeric,
  pricing_customer_price numeric,
  pricing_margin numeric,
  pricing_margin_percent numeric,
  pricing_gross_margin numeric,
  pricing_gross_margin_percent numeric,
  pricing_operating_cost numeric,
  pricing_net_margin_after_fees numeric,
  selected_provider text,
  pricing_strategy text,
  payment_intent_id text,
  provider_reference text,
  failure_reason text,
  pricing_decision jsonb,
  guard_result jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists jit_orders_trace_id_idx on public.jit_orders (trace_id);
create index if not exists jit_orders_status_idx on public.jit_orders (status);
create index if not exists jit_orders_created_at_idx on public.jit_orders (created_at desc);

create table if not exists public.settlements (
  id bigint generated by default as identity primary key,
  order_id text not null references public.jit_orders(id),
  trace_id text not null,
  customer_paid numeric not null,
  provider_cost numeric not null,
  margin numeric not null,
  pricing_input_amount numeric,
  pricing_provider_cost numeric,
  pricing_customer_price numeric,
  pricing_margin numeric,
  pricing_margin_percent numeric,
  pricing_gross_margin numeric,
  pricing_gross_margin_percent numeric,
  pricing_operating_cost numeric,
  pricing_net_margin_after_fees numeric,
  currency text not null default 'XOF',
  provider text not null,
  pricing_strategy text not null,
  pricing_decision jsonb,
  settled_at timestamptz not null default now()
);

create index if not exists settlements_order_id_idx on public.settlements (order_id);
create index if not exists settlements_trace_id_idx on public.settlements (trace_id);

create table if not exists public.guard_audit (
  id bigint generated by default as identity primary key,
  trace_id text not null,
  guard text not null,
  passed boolean not null,
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists guard_audit_trace_id_idx on public.guard_audit (trace_id);

create table if not exists public.webhook_events (
  id text primary key,
  type text not null,
  processed boolean not null default false,
  payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists webhook_events_type_idx on public.webhook_events (type);
create index if not exists webhook_events_created_at_idx on public.webhook_events (created_at desc);

create table if not exists public.inbound_webhook_events (
  id uuid primary key default gen_random_uuid(),
  provider text not null,
  provider_event_id text not null,
  signature_valid boolean not null,
  event_type text not null,
  domain_type text not null,
  domain_reference text,
  order_id text,
  payload jsonb not null,
  received_at timestamptz not null default now(),
  unique (provider, provider_event_id)
);

create index if not exists inbound_webhook_events_provider_idx on public.inbound_webhook_events (provider, received_at desc);

create table if not exists public.twilio_inbound_messages (
  id uuid primary key default gen_random_uuid(),
  provider_message_sid text not null unique,
  account_sid text,
  messaging_service_sid text,
  channel text not null check (channel in ('sms', 'whatsapp')),
  from_number text not null,
  to_number text not null,
  body text,
  profile_name text,
  num_media integer not null default 0,
  media_urls jsonb not null default '[]'::jsonb,
  raw_payload jsonb not null,
  signature_valid boolean not null,
  received_at timestamptz not null default now()
);

create index if not exists twilio_inbound_messages_received_at_idx on public.twilio_inbound_messages (received_at desc);
create index if not exists twilio_inbound_messages_channel_idx on public.twilio_inbound_messages (channel, received_at desc);
create index if not exists twilio_inbound_messages_from_number_idx on public.twilio_inbound_messages (from_number, received_at desc);

create table if not exists public.manual_billing_orders (
  id text primary key,
  trace_id text not null,
  service text not null check (service in ('sodeci', 'cie-postpaid', 'cie-prepaid', 'canal-plus')),
  country_code text not null default 'CI' check (country_code = 'CI'),
  account_reference text not null,
  package_code text,
  package_label text,
  quoted_amount numeric,
  currency text not null default 'XOF' check (currency = 'XOF'),
  status text not null check (status in ('quote_requested', 'quote_ready', 'payment_pending', 'paid', 'operator_started', 'operator_confirmed', 'completed', 'failed')),
  payment_session_id text,
  stripe_payment_status text check (stripe_payment_status in ('pending', 'paid', 'refunded')),
  admin_quote_notes text,
  admin_execution_notes text,
  telegram_message_id text,
  pricing_input_amount numeric,
  pricing_provider_cost numeric,
  pricing_customer_price numeric,
  pricing_margin numeric,
  pricing_margin_percent numeric,
  pricing_strategy text,
  pricing_decision jsonb,
  metadata jsonb,
  failure_reason text,
  customer jsonb not null,
  transitions jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists manual_billing_orders_service_idx on public.manual_billing_orders (service);
create index if not exists manual_billing_orders_status_idx on public.manual_billing_orders (status);
create index if not exists manual_billing_orders_created_at_idx on public.manual_billing_orders (created_at desc);
create index if not exists manual_billing_orders_trace_id_idx on public.manual_billing_orders (trace_id);

create table if not exists public.manual_billing_audit_events (
  id text primary key,
  order_id text not null references public.manual_billing_orders(id) on delete cascade,
  trace_id text not null,
  service text not null check (service in ('sodeci', 'cie-postpaid', 'cie-prepaid', 'canal-plus')),
  channel text not null check (channel in ('stripe_webhook', 'telegram_send', 'telegram_callback', 'whatsapp_send', 'admin', 'automation', 'system')),
  event text not null,
  outcome text not null check (outcome in ('attempted', 'received', 'processed', 'delivered', 'duplicate', 'failed', 'skipped')),
  detail text,
  payload jsonb,
  recorded_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists manual_billing_audit_events_order_id_idx on public.manual_billing_audit_events (order_id);
create index if not exists manual_billing_audit_events_trace_id_idx on public.manual_billing_audit_events (trace_id);
create index if not exists manual_billing_audit_events_channel_idx on public.manual_billing_audit_events (channel);
create index if not exists manual_billing_audit_events_recorded_at_idx on public.manual_billing_audit_events (recorded_at desc);

create table if not exists public.soutrali_tracked_orders (
  id text primary key,
  trace_id text not null,
  product_id text not null,
  product_name text not null,
  category text not null check (category in ('airtime', 'data', 'electricity', 'gift-card')),
  brand text not null check (brand in ('MTN', 'MOOV', 'ORANGE', 'CIE', 'JUMIA')),
  amount numeric not null,
  quoted_price numeric not null,
  currency text not null default 'XOF' check (currency = 'XOF'),
  customer_reference text not null,
  recipient_label text not null,
  sender_name text,
  beneficiary_phone_number text,
  recipient_email text,
  payment_session_id text,
  payment_status text check (payment_status in ('pending', 'paid', 'refunded')),
  selected_provider text not null check (selected_provider in ('reloadly', 'ding', 'dtone')),
  selected_execution_mode text not null check (selected_execution_mode in ('live', 'simulated')),
  provider_external_id text,
  provider_status text,
  recharge_code text,
  failure_reason text,
  return_path text not null,
  status text not null check (status in ('created', 'payment_pending', 'payment_received', 'provider_processing', 'completed', 'code_ready', 'refunded', 'failed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists soutrali_tracked_orders_trace_id_idx on public.soutrali_tracked_orders (trace_id);
create index if not exists soutrali_tracked_orders_status_idx on public.soutrali_tracked_orders (status);
create index if not exists soutrali_tracked_orders_category_idx on public.soutrali_tracked_orders (category);
create index if not exists soutrali_tracked_orders_created_at_idx on public.soutrali_tracked_orders (created_at desc);

create table if not exists public.internal_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.transfer_providers (
  id text primary key,
  name text not null,
  logo_url text not null default '',
  tagline text not null default '',
  best_for text not null default '',
  availability_summary text not null default '',
  corridor_focus text not null default '',
  payout_networks text[] not null default '{}',
  strengths text[] not null default '{}',
  exchange_rate_score numeric not null default 0,
  exchange_rate numeric not null default 0,
  fee_score numeric not null default 0,
  speed_score numeric not null default 0,
  ease_score numeric not null default 0,
  efficiency_score numeric not null default 0,
  mobile_wallet_speed numeric not null default 0,
  bank_deposit_speed numeric not null default 0,
  referral_link text not null default '',
  sort_order integer not null default 100,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists transfer_providers_name_idx on public.transfer_providers (name);
create index if not exists transfer_providers_sort_order_idx on public.transfer_providers (sort_order);

alter table public.jit_orders enable row level security;
alter table public.settlements enable row level security;
alter table public.guard_audit enable row level security;
alter table public.webhook_events enable row level security;
alter table public.inbound_webhook_events enable row level security;
alter table public.twilio_inbound_messages enable row level security;
alter table public.manual_billing_orders enable row level security;
alter table public.manual_billing_audit_events enable row level security;
alter table public.soutrali_tracked_orders enable row level security;
alter table public.internal_settings enable row level security;
alter table public.transfer_providers enable row level security;

revoke all on public.jit_orders from anon, authenticated;
revoke all on public.settlements from anon, authenticated;
revoke all on public.guard_audit from anon, authenticated;
revoke all on public.webhook_events from anon, authenticated;
revoke all on public.inbound_webhook_events from anon, authenticated;
revoke all on public.twilio_inbound_messages from anon, authenticated;
revoke all on public.manual_billing_orders from anon, authenticated;
revoke all on public.manual_billing_audit_events from anon, authenticated;
revoke all on public.soutrali_tracked_orders from anon, authenticated;
revoke all on public.internal_settings from anon, authenticated;
grant select, insert, update on public.inbound_webhook_events to service_role;
grant select, insert, update on public.twilio_inbound_messages to service_role;
grant select, insert, update on public.internal_settings to service_role;
grant select on public.transfer_providers to anon, authenticated;
revoke insert, update, delete, truncate, references, trigger on public.transfer_providers from anon, authenticated;

do $$
begin
  if exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relname = 'transfer_providers' and c.relkind = 'r'
  ) then
    execute 'alter table public.transfer_providers enable row level security';
    execute 'grant select on public.transfer_providers to anon, authenticated';
    execute 'revoke insert, update, delete, truncate, references, trigger on public.transfer_providers from anon, authenticated';

    if not exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = 'transfer_providers'
        and policyname = 'Public can read transfer providers'
    ) then
      execute 'create policy "Public can read transfer providers" on public.transfer_providers for select to anon, authenticated using (true)';
    end if;
  end if;
end $$;

create or replace view public.profitability_reporting
with (security_invoker = true) as
with latest_settlement as (
  select distinct on (s.order_id)
    s.order_id,
    s.trace_id,
    s.pricing_input_amount,
    s.pricing_provider_cost,
    s.pricing_customer_price,
    s.pricing_margin,
    s.pricing_margin_percent,
    s.pricing_gross_margin,
    s.pricing_gross_margin_percent,
    s.pricing_operating_cost,
    s.pricing_net_margin_after_fees,
    s.provider,
    s.pricing_strategy,
    s.pricing_decision,
    s.settled_at
  from public.settlements s
  order by s.order_id, s.settled_at desc
)
select
  'jit'::text as flow_type,
  j.id as order_id,
  j.trace_id,
  j.product_type as service_category,
  j.product_id as service_reference,
  j.customer_reference,
  j.recipient_label,
  null::text as customer_name,
  null::text as customer_email,
  j.status,
  j.currency,
  coalesce(ls.pricing_input_amount, j.pricing_input_amount, j.amount) as input_amount,
  coalesce(ls.pricing_provider_cost, j.pricing_provider_cost, j.provider_cost) as provider_cost,
  coalesce(ls.pricing_customer_price, j.pricing_customer_price, j.quoted_price) as customer_price,
  coalesce(ls.pricing_margin, j.pricing_margin, j.margin) as net_margin,
  coalesce(ls.pricing_margin_percent, j.pricing_margin_percent) as net_margin_percent,
  coalesce(ls.pricing_gross_margin, j.pricing_gross_margin) as gross_margin,
  coalesce(ls.pricing_gross_margin_percent, j.pricing_gross_margin_percent) as gross_margin_percent,
  coalesce(ls.pricing_operating_cost, j.pricing_operating_cost) as operating_cost,
  coalesce(ls.pricing_net_margin_after_fees, j.pricing_net_margin_after_fees) as net_margin_after_fees,
  coalesce(ls.provider, j.selected_provider) as provider,
  coalesce(ls.pricing_strategy, j.pricing_strategy) as pricing_strategy,
  coalesce(ls.pricing_decision, j.pricing_decision) as pricing_decision,
  j.failure_reason,
  ls.settled_at as realized_at,
  j.created_at,
  j.updated_at,
  (j.status = 'settled') as realized
from public.jit_orders j
left join latest_settlement ls on ls.order_id = j.id

union all

select
  'manual_billing'::text as flow_type,
  m.id as order_id,
  m.trace_id,
  m.service as service_category,
  coalesce(m.package_code, m.account_reference) as service_reference,
  m.account_reference as customer_reference,
  coalesce(m.customer ->> 'recipientName', m.account_reference) as recipient_label,
  m.customer ->> 'customerName' as customer_name,
  m.customer ->> 'customerEmail' as customer_email,
  m.status,
  m.currency,
  m.pricing_input_amount as input_amount,
  m.pricing_provider_cost as provider_cost,
  coalesce(m.pricing_customer_price, m.quoted_amount) as customer_price,
  m.pricing_margin as net_margin,
  m.pricing_margin_percent as net_margin_percent,
  case when m.pricing_decision ? 'grossMargin' then (m.pricing_decision ->> 'grossMargin')::numeric else null end as gross_margin,
  case when m.pricing_decision ? 'grossMarginPercent' then (m.pricing_decision ->> 'grossMarginPercent')::numeric else null end as gross_margin_percent,
  case when m.pricing_decision ? 'operatingCost' then (m.pricing_decision ->> 'operatingCost')::numeric else null end as operating_cost,
  case when m.pricing_decision ? 'netMarginAfterFees' then (m.pricing_decision ->> 'netMarginAfterFees')::numeric else null end as net_margin_after_fees,
  case when m.pricing_decision ? 'provider' then m.pricing_decision ->> 'provider' else null end as provider,
  m.pricing_strategy,
  m.pricing_decision,
  m.failure_reason,
  case when m.status = 'completed' then m.updated_at else null end as realized_at,
  m.created_at,
  m.updated_at,
  (m.status = 'completed') as realized
from public.manual_billing_orders m;

revoke all on public.profitability_reporting from anon, authenticated;
grant select on public.profitability_reporting to service_role;

create or replace view public.security_diagnostics
with (security_invoker = true) as
with target_tables as (
  select *
  from (
    values
      ('jit_orders'::text, 'sensitive'::text, 'locked_down'::text),
      ('settlements', 'sensitive', 'locked_down'),
      ('guard_audit', 'sensitive', 'locked_down'),
      ('webhook_events', 'sensitive', 'locked_down'),
      ('onboarding_drafts', 'sensitive', 'locked_down'),
      ('customers', 'sensitive', 'locked_down'),
      ('customer_profiles', 'sensitive', 'locked_down'),
      ('customer_contact_methods', 'sensitive', 'locked_down'),
      ('trusted_devices', 'sensitive', 'locked_down'),
      ('auth_factors', 'sensitive', 'locked_down'),
      ('customer_limits', 'sensitive', 'locked_down'),
      ('customer_risk_profiles', 'sensitive', 'locked_down'),
      ('sanctions_screenings', 'sensitive', 'locked_down'),
      ('compliance_cases', 'sensitive', 'locked_down'),
      ('case_actions', 'sensitive', 'locked_down'),
      ('inbound_webhook_events', 'sensitive', 'locked_down'),
      ('twilio_inbound_messages', 'sensitive', 'locked_down'),
      ('manual_billing_orders', 'sensitive', 'locked_down'),
      ('manual_billing_audit_events', 'sensitive', 'locked_down'),
      ('soutrali_tracked_orders', 'sensitive', 'locked_down'),
      ('internal_settings', 'sensitive', 'locked_down'),
      ('transfer_providers', 'public_read_only', 'public_read_only')
  ) as t(table_name, classification, expected_exposure)
), relations as (
  select
    t.table_name,
    t.classification,
    t.expected_exposure,
    c.oid,
    c.relrowsecurity,
    c.relname is not null as exists_in_schema
  from target_tables t
  left join pg_class c on c.relname = t.table_name and c.relkind = 'r'
  left join pg_namespace n on n.oid = c.relnamespace and n.nspname = 'public'
  where c.oid is null or n.nspname = 'public'
), policies as (
  select tablename, count(*)::int as policy_count
  from pg_policies
  where schemaname = 'public'
  group by tablename
)
select
  r.table_name,
  r.classification::text as classification,
  r.exists_in_schema,
  coalesce(r.relrowsecurity, false) as row_security_enabled,
  coalesce(p.policy_count, 0) as policy_count,
  case when r.oid is not null then has_table_privilege('anon', r.oid, 'SELECT') else false end as anon_select,
  case when r.oid is not null then has_table_privilege('anon', r.oid, 'INSERT') else false end as anon_insert,
  case when r.oid is not null then has_table_privilege('anon', r.oid, 'UPDATE') else false end as anon_update,
  case when r.oid is not null then has_table_privilege('anon', r.oid, 'DELETE') else false end as anon_delete,
  case when r.oid is not null then has_table_privilege('authenticated', r.oid, 'SELECT') else false end as authenticated_select,
  case when r.oid is not null then has_table_privilege('authenticated', r.oid, 'INSERT') else false end as authenticated_insert,
  case when r.oid is not null then has_table_privilege('authenticated', r.oid, 'UPDATE') else false end as authenticated_update,
  case when r.oid is not null then has_table_privilege('authenticated', r.oid, 'DELETE') else false end as authenticated_delete,
  case when r.oid is not null then has_table_privilege('service_role', r.oid, 'SELECT') else false end as service_role_select,
  r.expected_exposure::text as expected_exposure,
  case
    when not r.exists_in_schema then 'missing'
    when r.classification = 'sensitive'
      and coalesce(r.relrowsecurity, false)
      and not (case when r.oid is not null then has_table_privilege('anon', r.oid, 'SELECT') else false end)
      and not (case when r.oid is not null then has_table_privilege('anon', r.oid, 'INSERT') else false end)
      and not (case when r.oid is not null then has_table_privilege('anon', r.oid, 'UPDATE') else false end)
      and not (case when r.oid is not null then has_table_privilege('anon', r.oid, 'DELETE') else false end)
      and not (case when r.oid is not null then has_table_privilege('authenticated', r.oid, 'SELECT') else false end)
      and not (case when r.oid is not null then has_table_privilege('authenticated', r.oid, 'INSERT') else false end)
      and not (case when r.oid is not null then has_table_privilege('authenticated', r.oid, 'UPDATE') else false end)
      and not (case when r.oid is not null then has_table_privilege('authenticated', r.oid, 'DELETE') else false end)
      then 'ok'
    when r.classification = 'public_read_only'
      and coalesce(r.relrowsecurity, false)
      and (case when r.oid is not null then has_table_privilege('anon', r.oid, 'SELECT') else false end)
      and not (case when r.oid is not null then has_table_privilege('anon', r.oid, 'INSERT') else false end)
      and not (case when r.oid is not null then has_table_privilege('anon', r.oid, 'UPDATE') else false end)
      and not (case when r.oid is not null then has_table_privilege('anon', r.oid, 'DELETE') else false end)
      then 'ok'
    else 'review'
  end::text as status
from relations r
left join policies p on p.tablename = r.table_name;

revoke all on public.security_diagnostics from anon, authenticated;
grant select on public.security_diagnostics to service_role;

comment on table public.manual_billing_orders is 'Durable record for SODECI, CIE postpaid, and Canal+ manual billing orders orchestrated through Stripe and Telegram.';
comment on table public.webhook_events is 'Stripe webhook idempotency log shared by JIT and manual billing flows.';
comment on table public.manual_billing_audit_events is 'Queryable audit evidence for manual billing webhook, Telegram, admin, and automation events.';
comment on table public.internal_settings is 'Server-managed internal configuration for operational screens and alerts.';
comment on table public.transfer_providers is 'Ranked diaspora transfer providers displayed on the compare homepage.';
comment on view public.profitability_reporting is 'Unified profitability analytics surface for JIT and manual billing flows.';
comment on view public.security_diagnostics is 'Current RLS and grant posture for sensitive public-schema tables and intentionally public read-only tables.';