insert into public.transfer_providers (
  id,
  name,
  logo_url,
  tagline,
  best_for,
  availability_summary,
  corridor_focus,
  payout_networks,
  strengths,
  exchange_rate_score,
  exchange_rate,
  fee_score,
  speed_score,
  ease_score,
  efficiency_score,
  mobile_wallet_speed,
  bank_deposit_speed,
  referral_link,
  sort_order,
  active
)
values
  ('taptap-send', 'Taptap Send', '/logos/taptapsend.png', 'Best overall when you need strong XOF payout with minimal friction.', 'Fast mobile wallet delivery to West Africa', 'Strong for card-funded diaspora transfers with consistent wallet speed.', 'US, UK, and Europe to Francophone West Africa', '{"Mobile wallet","Bank deposit"}', '{"Strong exchange quality","Fast wallet settlement","Low fee positioning"}', 9.1, 1386.2, 8.9, 9.2, 8.8, 8.9, 9.4, 8.6, 'https://www.taptapsend.com', 10, true),
  ('lemfi', 'Lemfi', '/logos/lemfi.png', 'Balanced payout quality with strong bank deposit execution.', 'Bank deposits and frequent repeat senders', 'Well-suited for senders comparing payout quality and account-based delivery.', 'North America and Europe into major African banking corridors', '{"Bank deposit","Wallet in selected corridors"}', '{"Strong bank payout speed","Good fee consistency","Clean app experience"}', 8.8, 1384.75, 8.7, 8.9, 8.6, 8.7, 8.8, 9.1, 'https://www.lemfi.com', 20, true),
  ('nala', 'NALA', '/logos/nala.png', 'Consumer-friendly UX with reliable everyday diaspora sending flows.', 'Simple repeat transfers from mobile-first users', 'Good for straightforward recurring transfers where ease matters as much as rate.', 'US, UK, and EU diaspora corridors into Africa', '{"Bank deposit","Mobile wallet"}', '{"High ease-of-use","Solid wallet support","Strong recurring-send fit"}', 8.7, 1382.53, 8.5, 8.8, 8.9, 8.5, 8.7, 8.4, 'https://www.nala.com', 30, true),
  ('send-app', 'Send App', '/logos/sendapp.png', 'Useful when Flutterwave-linked rails give a smoother payout path.', 'Flutterwave-connected payout routes', 'A pragmatic option when payout rail availability matters more than absolute rate leadership.', 'Diaspora corridors supported through Flutterwave-linked infrastructure', '{"Bank deposit","Wallet in supported markets"}', '{"Reasonable pricing","Practical payout coverage","Simple checkout flow"}', 8.4, 1379.4, 8.6, 8.3, 8.7, 8.4, 8.5, 8.2, 'https://send.flutterwave.com', 40, true),
  ('remitly', 'Remitly', '/logos/remitly.png', 'Broad brand familiarity and dependable delivery for mainstream senders.', 'Brand-trust oriented customers', 'Often chosen when familiarity and predictable experience outweigh pure payout optimization.', 'Large global diaspora corridors across bank and cash-out routes', '{"Bank deposit","Cash pickup","Mobile wallet"}', '{"Strong consumer trust","Wide corridor coverage","Reliable delivery"}', 8.1, 1375.15, 8.0, 8.2, 8.6, 8.0, 8.0, 8.5, 'https://www.remitly.com', 50, true)
on conflict (id) do update
set
  name = excluded.name,
  logo_url = excluded.logo_url,
  tagline = excluded.tagline,
  best_for = excluded.best_for,
  availability_summary = excluded.availability_summary,
  corridor_focus = excluded.corridor_focus,
  payout_networks = excluded.payout_networks,
  strengths = excluded.strengths,
  exchange_rate_score = excluded.exchange_rate_score,
  exchange_rate = excluded.exchange_rate,
  fee_score = excluded.fee_score,
  speed_score = excluded.speed_score,
  ease_score = excluded.ease_score,
  efficiency_score = excluded.efficiency_score,
  mobile_wallet_speed = excluded.mobile_wallet_speed,
  bank_deposit_speed = excluded.bank_deposit_speed,
  referral_link = excluded.referral_link,
  sort_order = excluded.sort_order,
  active = excluded.active,
  updated_at = now();