alter table public.manual_billing_orders
  add column if not exists pricing_input_amount numeric,
  add column if not exists pricing_provider_cost numeric,
  add column if not exists pricing_customer_price numeric,
  add column if not exists pricing_margin numeric,
  add column if not exists pricing_margin_percent numeric,
  add column if not exists pricing_strategy text,
  add column if not exists pricing_decision jsonb;

comment on column public.manual_billing_orders.pricing_input_amount is 'Base bill or package amount before AfriSendIQ markup.';
comment on column public.manual_billing_orders.pricing_provider_cost is 'Underlying provider/base cost used by the profit engine for the manual billing order.';
comment on column public.manual_billing_orders.pricing_customer_price is 'Customer-facing quoted amount generated by the AfriSendIQ profit engine.';
comment on column public.manual_billing_orders.pricing_margin is 'Net AfriSendIQ margin amount from the profit engine summary.';
comment on column public.manual_billing_orders.pricing_margin_percent is 'Net AfriSendIQ margin percentage from the profit engine summary.';
comment on column public.manual_billing_orders.pricing_strategy is 'Profit engine pricing strategy used for the manual billing quote.';
comment on column public.manual_billing_orders.pricing_decision is 'Full pricing decision payload captured for manual billing observability.';

update public.manual_billing_orders
set
  pricing_input_amount = case when metadata -> 'manualPricing' ->> 'inputAmount' is not null then (metadata -> 'manualPricing' ->> 'inputAmount')::numeric else null end,
  pricing_provider_cost = case when metadata -> 'manualPricing' ->> 'providerCost' is not null then (metadata -> 'manualPricing' ->> 'providerCost')::numeric else null end,
  pricing_customer_price = case when metadata -> 'manualPricing' ->> 'customerPrice' is not null then (metadata -> 'manualPricing' ->> 'customerPrice')::numeric else null end,
  pricing_margin = case when metadata -> 'manualPricing' ->> 'afrisendiqMargin' is not null then (metadata -> 'manualPricing' ->> 'afrisendiqMargin')::numeric else null end,
  pricing_margin_percent = case when metadata -> 'manualPricing' ->> 'afrisendiqMarginPercent' is not null then (metadata -> 'manualPricing' ->> 'afrisendiqMarginPercent')::numeric else null end,
  pricing_strategy = metadata -> 'manualPricing' ->> 'pricingStrategy',
  pricing_decision = metadata -> 'manualPricing' -> 'pricingDecision'
where metadata ? 'manualPricing';
